### ISSUE TITLE
MacOS Premid prompts firewall every system reboot

### ISSUE THREAD

**Issue by KenaiTheWolf** [PreMiD/PreMiD#488]
**Describe the bug**
macOS Premid prompts firewall dialogue for allow / deny ports every system reboot

**To Reproduce**
1. Install Premid
2. Reboot

**Expected behavior**
The premid app should show itself to the firewall,  and stay persistently stored as an application with the allow or deny state saved.

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.6 Beta 1 (Happens on stable)
 - Browser Firefox
 - Version Premid 2.3.1 Firefox 78.0b6

**Comment by kawakaami** [comment]
Probably it happens because app is not signed. We can't do anything (and I think it is only on 10.x version because I didn't saw any people that reporting this issue like that on 14.x 15.x)

**Comment by KenaiTheWolf** [comment]
MacOS versions are 10.15.x, they've been like this since 2001. There is no 14.x or 15.x, 10.15.x is the most recent version. 
As far as the app not being signed - that's a different system called gatekeeper that warns users. 
It only prompts you the first time you run the application, not to mention, I have gatekeeper disabled, SIP is disabled, etc.

**Comment by kawakaami** [comment]
As I said, I didn't saw any people that uses macOS with this issue (and no one was reporting it tho) so probably macOS version or something different.

**Comment by kawakaami** [comment]
Yeah about these macOS version my bad.

**Comment by KenaiTheWolf** [comment]
That doesn’t hold water. I’ve reproduced the issue on 10.14, 10.15 & 11.0, not to mention on two machines and a clean OS install.

**Comment by kawakaami** [comment]
Will ask other support agent that uses macOS maybe he know how to fix it. I'll respond there when I get response.

**Comment by kawakaami** [comment]
Did you mean this dialogue? ![premid](https://cdn.discordapp.com/attachments/526736087377248257/739185109395308624/Screen_Shot_2020-08-01_at_2.17.08_PM.png)

**Comment by KenaiTheWolf** [comment]
Yep, that’s the one.

**Comment by kawakaami** [comment]
![premid](https://media.discordapp.net/attachments/526736087377248257/739186821543493632/20200801_142411.jpg) As it says, it can't be avoided because app is not signed.

**Comment by KenaiTheWolf** [comment]
So why not change the behavior of the application so it doesn’t check its own integrity when it’s opened to allow OS X to auto sign? The system will automatically check the integrity of the application on first launch and ask the user if they want to launch.

**Comment by kawakaami** [comment]
Probably autoupdater checks it. We are sorry for that. In v3 it will maybe change.

**Comment by KenaiTheWolf** [comment]
It's all good, could you tell me about the build system by chance, I can codesign with my dev account, but I want to see if the signature will even stay valid.

**Comment by kawakaami** [comment]
We will try do all things in v3 to eliminate these things 😁

**Comment by KenaiTheWolf** [comment]
I understand you're on hiatus - just wanted to throw an update and I wish you good luck with resolving this, that said, here's what I've done.

I just tried to code sign the application with Xcode, and it doesn't look good. My personal account won't allow me to code sign this for the 7 day period it's supposed to be able to be signed for.

**Comment by ririxichan** [comment]
PreMiD v3 is not on electron, so it will work in different way and probably we will sign it. Just keep watching for v3 release :)

**Comment by ririxidev** [comment]
@KenaiTheWolf, I think that with macOS Big Sur release, it should be fixed tho 🤔

**Comment by DarthGigi** [comment]
> @KenaiTheWolf, I think that with macOS Big Sur release, it should be fixed tho 🤔

I'm on macOS Big Sur 11.5.1 (20G80) and it still shows the same dialogue every time I restart the PreMiD app.

**Comment by EncryptedDev** [comment]
This should be resolved in v3

**Comment by Timeraa** [comment]
is this still an issue? Because I can't reproduce this on Ventura?

**Comment by KenaiTheWolf** [comment]
I can still reproduce this on the current developer beta of Ventura. I would assume it's still a bug if the application is unsigned and doesn't have the proper entitlements as that's what's causing the issue to begin with.

**Comment by KenaiTheWolf** [comment]
I can still reproduce this bug on the latest macOS 13 and macOS 14 builds.

**Comment by Timeraa** [comment]
Hmm, I sadly don't have that issue at all on my Mac, but I am soon going to be updating the app and I hope the issue is going to be gone by then

**Comment by Timeraa** [comment]
App isn't needed anymore so this can be closed.
